import jsPDF from 'jspdf';

const dateStr = () => new Date().toISOString().split('T')[0];

function downloadCSV(rows, columns, filename) {
  const header = columns.join(',');
  const csv = [header, ...rows.map(r => columns.map(c => {
    const val = String(r[c] ?? '').replace(/"/g, '""');
    return val.includes(',') || val.includes('"') || val.includes('\n') ? `"${val}"` : val;
  }).join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

export function exportBetsCSV(bets) {
  const rows = bets.map(b => ({
    Date: new Date(b.created_at).toLocaleDateString(),
    Event: b.match || '',
    Sportsbook: b.sportsbook || '',
    'Bet Type': b.type || '',
    Odds: b.odds || '',
    Stake: b.stake || '',
    Payout: b.result === 'win' && b.pnl ? (parseFloat(b.stake || 0) + parseFloat(b.pnl || 0)).toFixed(2) : '0',
    Result: b.result || '',
    'P&L': b.pnl != null ? parseFloat(b.pnl).toFixed(2) : '',
    Notes: b.notes || '',
  }));
  downloadCSV(rows, ['Date', 'Event', 'Sportsbook', 'Bet Type', 'Odds', 'Stake', 'Payout', 'Result', 'P&L', 'Notes'], `sharpr-bets-${dateStr()}.csv`);
}

export function exportTradesCSV(trades) {
  const rows = trades.map(t => ({
    Date: new Date(t.created_at).toLocaleDateString(),
    Ticker: t.ticker || '',
    Direction: t.direction || '',
    Quantity: t.qty || '',
    Entry: t.entry || '',
    Exit: t.exit || '',
    'P&L': t.pnl != null ? parseFloat(t.pnl).toFixed(2) : '',
    Status: t.status || '',
    Setup: t.setup || '',
    Notes: t.notes || '',
  }));
  downloadCSV(rows, ['Date', 'Ticker', 'Direction', 'Quantity', 'Entry', 'Exit', 'P&L', 'Status', 'Setup', 'Notes'], `sharpr-trades-${dateStr()}.csv`);
}

export function exportBetsPDF(bets) {
  const doc = new jsPDF();
  doc.setFontSize(20); doc.setTextColor(79, 142, 247);
  doc.text('Sharpr — Betting Report', 14, 22);
  doc.setFontSize(10); doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);

  const settled = bets.filter(b => b.result !== 'pending');
  const wins = settled.filter(b => b.result === 'win').length;
  const totalPnl = settled.reduce((s, b) => s + (b.pnl || 0), 0);
  const totalStake = settled.reduce((s, b) => s + (b.stake || 0), 0);

  doc.setFontSize(11); doc.setTextColor(40);
  doc.text(`Total Bets: ${bets.length}  |  Settled: ${settled.length}  |  Win Rate: ${settled.length ? Math.round(wins / settled.length * 100) : 0}%  |  P&L: $${totalPnl.toFixed(2)}  |  ROI: ${totalStake ? (totalPnl / totalStake * 100).toFixed(1) : 0}%`, 14, 40);

  // Table
  let y = 50;
  doc.setFontSize(8); doc.setTextColor(80);
  const cols = ['Date', 'Event', 'Type', 'Odds', 'Stake', 'Result', 'P&L'];
  const widths = [22, 55, 22, 18, 18, 18, 20];
  cols.forEach((c, i) => { doc.text(c, 14 + widths.slice(0, i).reduce((a, b) => a + b, 0), y); });
  y += 6; doc.setDrawColor(200); doc.line(14, y - 2, 196, y - 2);

  doc.setTextColor(60);
  bets.forEach(b => {
    if (y > 280) { doc.addPage(); y = 20; }
    const row = [
      new Date(b.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      (b.match || '').slice(0, 28), b.type || '', b.odds || '',
      '$' + (b.stake || 0), b.result || '',
      b.pnl != null ? '$' + parseFloat(b.pnl).toFixed(2) : '',
    ];
    row.forEach((v, i) => { doc.text(String(v), 14 + widths.slice(0, i).reduce((a, b) => a + b, 0), y); });
    y += 5;
  });

  doc.setFontSize(7); doc.setTextColor(150);
  doc.text('Generated by Sharpr (sharprapp.com) — For informational purposes only', 14, 290);
  doc.save(`sharpr-bets-report-${dateStr()}.pdf`);
}

export function exportTradesPDF(trades) {
  const doc = new jsPDF();
  doc.setFontSize(20); doc.setTextColor(79, 142, 247);
  doc.text('Sharpr — Trading Report', 14, 22);
  doc.setFontSize(10); doc.setTextColor(100);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 30);

  const settled = trades.filter(t => t.status !== 'open');
  const wins = settled.filter(t => t.status === 'win').length;
  const totalPnl = settled.reduce((s, t) => s + (t.pnl || 0), 0);

  doc.setFontSize(11); doc.setTextColor(40);
  doc.text(`Total Trades: ${trades.length}  |  Settled: ${settled.length}  |  Win Rate: ${settled.length ? Math.round(wins / settled.length * 100) : 0}%  |  P&L: $${totalPnl.toFixed(2)}`, 14, 40);

  let y = 50;
  doc.setFontSize(8); doc.setTextColor(80);
  const cols = ['Date', 'Ticker', 'Dir', 'Qty', 'Entry', 'Exit', 'P&L', 'Status'];
  const widths = [22, 20, 16, 16, 22, 22, 22, 20];
  cols.forEach((c, i) => { doc.text(c, 14 + widths.slice(0, i).reduce((a, b) => a + b, 0), y); });
  y += 6; doc.setDrawColor(200); doc.line(14, y - 2, 196, y - 2);

  doc.setTextColor(60);
  trades.forEach(t => {
    if (y > 280) { doc.addPage(); y = 20; }
    const row = [
      new Date(t.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }),
      t.ticker || '', t.direction || '', t.qty || '',
      t.entry ? '$' + parseFloat(t.entry).toFixed(2) : '',
      t.exit ? '$' + parseFloat(t.exit).toFixed(2) : '',
      t.pnl != null ? '$' + parseFloat(t.pnl).toFixed(2) : '',
      t.status || '',
    ];
    row.forEach((v, i) => { doc.text(String(v), 14 + widths.slice(0, i).reduce((a, b) => a + b, 0), y); });
    y += 5;
  });

  doc.setFontSize(7); doc.setTextColor(150);
  doc.text('Generated by Sharpr (sharprapp.com) — For informational purposes only', 14, 290);
  doc.save(`sharpr-trades-report-${dateStr()}.pdf`);
}
